### ISSUE TITLE
Tutorial 1

### ISSUE THREAD

**Issue by AnnaGolubeva** [PIQuIL/QuCumber#85] opened 2019-06-05 17:31 UTC
running locally in jupyter notebook (ananconda, python 3.6, torch 1.1.0);
kernel is dying when cell with "callbacks" is executed

**Comment by emerali** [comment] 2019-06-05 18:01
debugged this offline, seems to be a python version issue (ref. https://github.com/pytorch/pytorch/issues/17237)

will push a fix soon

**Comment by mbeach42** [comment] 2019-06-05 18:04
I can't seem to reproduce this.

**Comment by emerali** [comment] 2019-06-05 18:06
yea it's a python 3.6.0 bug (possibly also 3.6.1)

**Comment by mbeach42** [comment] 2019-06-05 18:33
OK, let's drop support for anything below 3.6.2.

**Comment by emerali** [comment] 2019-06-05 19:09
3.6.1 does still seem to work, so i think we'll keep that one

3.6.0 and below will all be dropped, though

**Comment by emerali** [comment] 2019-06-05 19:30
resolved by #86

**Closed by emerali** 2019-06-05 19:30 UTC
Labels: bug
