### ISSUE TITLE
Jupyter tutorials don't render on GitHub

### ISSUE THREAD

**Issue by rgmelko** [PIQuIL/QuCumber#62] opened 2018-09-21 19:14 UTC
WTF is that?  Only tutorial 1 renders properly on the master branch

**Comment by Roger-luo** [comment] 2018-09-21 19:27
Works well on GHERKIN.

**Comment by mbeach42** [comment] 2018-09-21 19:30
Can't reproduce. On chrome version 69.0 they seems to render perfectly.

**Comment by Roger-luo** [comment] 2018-09-21 19:38
I think this is just a GitHub issue. But we should support https://mybinder.org, there is awesome for browsing notebooks.

**Comment by emerali** [comment] 2018-09-21 20:05
I've actually already setup mybinder support. In the documentation, there's a link at the top of each rendered jupyter notebook.

example: https://qucumber.readthedocs.io/en/stable/_examples/Tutorial1_TrainPosRealWavefunction/tutorial_quantum_ising.html

also, the jupyter notebooks load fine for me thru github (i'm using firefox)

**Comment by Roger-luo** [comment] 2018-09-21 20:08
I see. That's nice. I'll close this, since this is not our problem.

**Closed by Roger-luo** 2018-09-21 20:08 UTC
Labels: Priority: Low
